name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pygame pytest black flake8 mypy
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
    
    - name: Run black
      run: python -m black --check .
      continue-on-error: true

    - name: Run flake8
      run: python -m flake8 .
      continue-on-error: true

    - name: Run mypy
      run: python -m mypy . --no-error-summary
      continue-on-error: true

    - name: Run pytest
      run: python -m pytest tests -vv
      # continue-on-error: true